### ISSUE TITLE
Problema do site ficando todo verde.

### ISSUE THREAD

**Issue by EduardaMFerreira** [EduardaMFerreira/CopiaTemplate#3]
### Problema de Cores

Durante o uso do site, eu vi que quando clico no botão de finalizar compra, ele fica todo verde e não aparece mais nada.

Passos para chegar ao erro que eu vi:
- [ ] Selecione um produto
- [ ] Adicione um produto
- [ ] Clique em finalizar compra
- [ ] Veja o erro

![image](https://github.com/EduardaMFerreira/CopiaTemplate/assets/166639823/104584f6-3113-4556-bda6-b549fcaf288c)

@EduardaMFerreira veja esse problema
#1
